version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    versioning-strategy: increase
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: '-'
    ignore:
      - dependency-name: 'typescript'
      - dependency-name: 'sinon'
      - dependency-name: 'string-ansi'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
